// auto-generated by xpiler

using System;
using System.Collections.Generic;
using System.Text;

using x2;

namespace x2.Events
{
    public static class BuiltInType
    {
        public const int FlowStart = -1;
        public const int FlowStop = -2;
        public const int TimeoutEvent = -3;

        private static ConstsInfo<int> info;

        static BuiltInType()
        {
            info = new ConstsInfo<int>();
            info.Add("FlowStart", -1);
            info.Add("FlowStop", -2);
            info.Add("TimeoutEvent", -3);
        }

        public static string GetName(int value)
        {
            return info.GetName(value);
        }

        public static int Parse(string name)
        {
            return info.Parse(name);
        }

        public static bool TryParse(string name, out int result)
        {
            return info.TryParse(name, out result);
        }

    }
}
