// auto-generated by x2clr xpiler

using System;
using System.Collections.Generic;
using System.Text;

using x2;

namespace x2.Tests.Func
{
    public class HelloCaseEvent : Event
    {
        protected new static readonly Tag tag;

        public new static int TypeId { get { return tag.TypeId; } }

        private int foo_;
        private string bar_;

        public int Foo
        {
            get { return foo_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                foo_ = value;
            }
        }

        public string Bar
        {
            get { return bar_; }
            set
            {
                fingerprint.Touch(tag.Offset + 1);
                bar_ = value;
            }
        }

        static HelloCaseEvent()
        {
            tag = new Tag(Event.tag, typeof(HelloCaseEvent), 2,
                    1);
        }

        public new static HelloCaseEvent New()
        {
            return new HelloCaseEvent();
        }

        public HelloCaseEvent()
            : base(tag.NumProps)
        {
            Initialize();
        }

        protected HelloCaseEvent(int length)
            : base(length + tag.NumProps)
        {
            Initialize();
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            HelloCaseEvent o = (HelloCaseEvent)other;
            if (foo_ != o.foo_)
            {
                return false;
            }
            if (bar_ != o.bar_)
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(foo_);
            }
            if (touched[1])
            {
                hash.Update(tag.Offset + 1);
                hash.Update(bar_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return HelloCaseEvent.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            HelloCaseEvent o = (HelloCaseEvent)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (foo_ != o.foo_)
                {
                    return false;
                }
            }
            if (touched[1])
            {
                if (bar_ != o.bar_)
                {
                    return false;
                }
            }
            return true;
        }

        public override void Deserialize(Deserializer deserializer)
        {
            base.Deserialize(deserializer);
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                deserializer.Read(out foo_);
            }
            if (touched[1])
            {
                deserializer.Read(out bar_);
            }
        }

        public override void Deserialize(VerboseDeserializer deserializer)
        {
            base.Deserialize(deserializer);
            deserializer.Read("Foo", out foo_);
            deserializer.Read("Bar", out bar_);
        }

        public override void Serialize(Serializer serializer)
        {
            base.Serialize(serializer);
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                serializer.Write(foo_);
            }
            if (touched[1])
            {
                serializer.Write(bar_);
            }
        }

        public override void Serialize(VerboseSerializer serializer)
        {
            base.Serialize(serializer);
            serializer.Write("Foo", foo_);
            serializer.Write("Bar", bar_);
        }

        public override int GetLength()
        {
            int length = base.GetLength();
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                length += Serializer.GetLength(foo_);
            }
            if (touched[1])
            {
                length += Serializer.GetLength(bar_);
            }
            return length;
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" Foo={0}", foo_);
            stringBuilder.AppendFormat(" Bar=\"{0}\"", bar_.Replace("\"", "\\\""));
        }

        private void Initialize()
        {
            foo_ = 0;
            bar_ = "";
        }
    }
}
